name: "Podcast Generator using Docker and bash with python code."
author: "Amit Kumar Tech Lead."
Description: "A GitHub Action to generate a feed from a description: Podcast YAML file and commit to the repository.description: "
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "blue"
inputs:
  EMAIL:
    description: "The email address for the Committer."
    required: true
    default: ${{ github.actor }}@users.noreply.github.com
  NAME:
    description: "The name of the Committer."
    required: true
    default: ${{ github.actor }}
