name: "Podcast Generator using Docker and Bash with Python code."
author: "Amit Kumar Tech Lead."
Description: "GitHub Action to generate a podcast feed from YAML and commit the output."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "blue"
inputs:
  EMAIL:
    description: "The email address for the Committer."
    required: true
    default: ${{ github.actor }}@users.noreply.github.com
  NAME:
    description: "The name of the Committer."
    required: true
    default: ${{ github.actor }}
